#!/bin/bash

make="${MAKE:-make}"

cd system
$make $1 $2 || exit
cd ..

cd comms
$make $1 $2 || exit
cd ..

cd web
$make $1 $2 || exit
cd ..

cd TargetBus
$make $1 $2 || exit
cd ..

cd Hardware
$make $1 $2 || exit
cd ..

cd BusControlAPI
$make $1 $2 || exit
cd ..

cd Machines
$make $1 $2 || exit
cd ..

cd fonts
$make $1 $2 || exit
cd ..

cd TerminalEmulation
$make $1 $2 || exit
cd ..

cd FileFormats
$make $1 $2 || exit
cd ..

cd Display
$make $1 $2 || exit
cd ..

$make $1 $2 || exit
