"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"\t<meta charset=\"iso-8859-1\" />\n"
"\t<link rel=\"stylesheet\" href=\"style.css\" type=\"text/css\" />\n"
"\t<title>Bare metal Bootloader</title>\n"
"</head>\n"
"<body>\n"
"\t<h1>Bare metal Bootloader</h1>\n"
"\n"
"\t<p>%s</p>\n"
"\n"
"\t<form action=\"index.html\" method=\"post\" enctype=\"multipart/form-data\">\n"
"\t\t<table>\n"
"\t\t<tr>\n"
"\t\t\t<th>Kernel image file (kernel*.img)</th>\n"
"\t\t</tr>\n"
"\t\t<tr>\n"
"\t\t\t<td><input type=\"file\" name=\"kernelimg\" /></td>\n"
"\t\t</tr>\n"
"\t\t<tr>\n"
"\t\t\t<td><input type=\"submit\" value=\"Boot now!\" /></td>\n"
"\t\t</tr>\n"
"\t\t</table>\n"
"\t</form>\n"
"\n"
"\t<hr />\n"
"\t<p class=\"small\"><a href=\"https://github.com/rsta2/circle\" target=\"_blank\">Circle %s</a> running on %s</p>\n"
"</body>\n"
"</html>\n"
""