
# Generate font from binary

cellWidthPix = 8
cellHeightPix = 24
bytesAcross = 1
bytesPerChar = 24

with open ("../src/mc_trs80l3font.c", "w+") as outFile:
    outFile.write("// TRS80 Level 3 Font\n")
    outFile.write("// Autogenerated file - see GenFontTRS80Level3.py\n")
    outFile.write("unsigned char __pTRS80Level3FontBin[] = {\n")

    with open("TRS80FontLevel3.bin", "rb") as inFile:

        dat = inFile.read()
        print(len(dat))
        p = 0
        for c in range(192):
            outFile.write("// Char code 0x{:02x}\n".format(c))
            for j in range(24):
                outFile.write("0b")
                for i in range(8):
                    outFile.write("1" if dat[p] != 0 else "0")
                    p += 1
                outFile.write(",\n")
            outFile.write("\n")        

    outFile.write("};\n")

    outFile.write("\n#include \"wgfxfont.h\"\n")
    outFile.write("\nWgfxFont __TRS80Level3Font = {\n")
    outFile.write("    .cellX = " + str(cellWidthPix) + ",\n")
    outFile.write("    .cellY = " + str(cellHeightPix) + ",\n")
    outFile.write("    .bytesAcross = " + str(bytesAcross) + ",\n")
    outFile.write("    .bytesPerChar = " + str(bytesPerChar) + ",\n")
    outFile.write("    .pFontData = __pTRS80Level3FontBin,\n")
    outFile.write("    .fontNumChars = 192\n")
    outFile.write("};\n")

    

