# Generate font from image
from PIL import Image

with open ("../src/mc_trs80l1font.c", "w+") as outFile:
    outFile.write("// TRS80 Level 1 Font\n")
    outFile.write("// Autogenerated file - see GenFontTRS80Level1.py\n")
    outFile.write("unsigned char __pTRS80Level1FontBin[] = {\n")

    pngFile = Image.open("TRS80FontLevel1.PNG")
    print(pngFile.size)
    pngData = pngFile.load()
    print(pngData[7,7])

    borderWidth = 4
    pixWidth = 2
    pixHeight = 3
    cellWidthPix = 6;
    cellHeightPix = 8;
    bytesAcross = 1
    bytesPerChar = 8
    charCellWidth = 24
    charCellHeight = 72

    for rowChar in range(8):
        for colChar in range(32):
            outFile.write("// Char code 0x{:02x}\n".format(rowChar*32+colChar)) 
            for rowPix in range(cellHeightPix):
                outFile.write("0b")
                for colPix in range(cellWidthPix):
                    pixX = colChar*charCellWidth + colPix*pixWidth + borderWidth
                    pixY = rowChar*charCellHeight + rowPix*pixHeight + borderWidth
                    #print(rowChar, colChar, rowPix, colPix, pixX, pixY)
                    pix = pngData[pixX, pixY]
                    outFile.write("1" if pix[1] != 0 else "0")
                outFile.write(",\n")
            outFile.write("\n")        
    outFile.write("};\n")

    outFile.write("\n#include \"wgfxfont.h\"\n")
    outFile.write("\nWgfxFont __TRS80Level1Font = {\n")
    outFile.write("    .cellX = " + str(cellWidthPix) + ",\n")
    outFile.write("    .cellY = " + str(cellHeightPix) + ",\n")
    outFile.write("    .bytesAcross = " + str(bytesAcross) + ",\n")
    outFile.write("    .bytesPerChar = " + str(bytesPerChar) + ",\n")
    outFile.write("    .pFontData = __pTRS80Level1FontBin\n")
    outFile.write("};\n");

    
