/////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
// RIC Configurations
//
// Rob Dobson 2020
//
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// NOTE:
// In VSCode C++ raw strings can be removed - to reveal JSON with regex search and replace:
//      regex:    R"\((.*)\)"
//      replace:  $1
// And then reinserted with:
//      regex:    (\s*)(.*)
//      replace:  $1R"($2)"

const char* RIC_CONFIGURATIONS[] = {

// RIC configurations

// TODO - review core and priority for I2C task - should probably be core 1? not sure about priortity - prob higher than main loop tho

R"({)"
	R"("SysType":"RICMarty2",)"
	R"("CmdsAtStart":"",)"
	R"("WebUI":"",)"
	R"("FileManager": {)"
		R"("SPIFFSEnabled": 1,)"
		R"("SPIFFSFormatIfCorrupt": 1,)"
		R"("SDEnabled": 1,)"
		R"("DefaultSD": 1,)"
		R"("SDMOSI": 15,)"
		R"("SDMISO": 4,)"
		R"("SDCLK": 14,)"
		R"("SDCS": 13,)"
		R"("maxCacheBytes": 10000)"
	R"(},)"
	R"("Robot": {)"
		R"("Model":"MartyV2",)"
		R"("StatDisp":{"pixIdxPower":0, "pixIdxConn":2},)"
		R"("DemoButton":{"demoPin":5, "demoTraj":"demo","debounceMs":300,)"
			R"("longPressTraj":"longpress", "longPressMs":2000, "longPressRepMs": 4000, "longPressReps":500)"
		R"(},)"
		R"("Safeties":{"maxMs":5000,"ffEn":1,"ocEn":1},)"
		R"("PwrMgmt":{)"
			R"("initMotorsOn":1,)"
			R"("idle5vOffSecs":1800,)"
			R"("idlePowerDownSecs":2700,)"
			R"("battFullCapMAH":2500,)"
			R"("batLevels":[)"
				R"({"PC":3,"5VOn":0,"colr":"100000","blnk":"breathe","fullOff":1},)"
				R"({"PC":5,"5VOn":0,"colr":"100000","blnk":"breathe"},)"
				R"({"PC":10,"5VOn":1,"colr":"100000","blnk":"on"},)"
				R"({"PC":30,"5VOn":1,"colr":"100400","blnk":"on"},)"
				R"({"PC":100,"5VOn":1,"colr":"002000","blnk":"on"})"
			R"(],)"
			R"("extLevels":[)"
				R"({"PC":90,"colr":"000040","blnk":"breathe"},)"
				R"({"PC":100,"colr":"000040","blnk":"on"})"
			R"(])"
		R"(},)"
		R"("Buses": [{)"
			R"("name":"I2CA",)"
			R"("type":"I2C",)"
			R"("reqFIFOLen": 10,)"
			R"("i2cPort": 0,)"
			R"("sdaPin":"21",)"
			R"("sclPin":"22",)"
			R"("i2cFreq": 100000,)"
			R"("taskCore": 1,)"
			R"("taskPriority": 24)"
		R"(}],)"
		R"("HWElemDefaults": [{)"
				R"("type":"SmartServo",)"
				R"("bus":"I2CA",)"
				R"("poll":"status",)"
				R"("pollHz":100.0,)"
				R"("mul":600,)"
				R"("buz":1,)"
				R"("kp":1000,)"
				R"("ki":0,)"
				R"("kd":1000,)"
				R"("ci":80,)"
				R"("cs":2500,)"
				R"("ocSafety":1)"
			R"(},)"
			R"({)"
				R"("type":"RSAddOn",)"
				R"("poll":"status",)"
				R"("pollRd":10,)"
				R"("pollHz":10.0)"
			R"(})"
		R"(],)"
		R"("HWElems": [{)"
				R"("name":"LeftHip",)"
				R"("type":"SmartServo",)"
				R"("addr":"0x10",)"
				R"("dir":1,)"
				R"("pmn":270,)"
				R"("pmx":760,)"
				R"("IDNo":0)"
			R"(},)"
			R"({)"
				R"("name":"LeftTwist",)"
				R"("type":"SmartServo",)"
				R"("addr":"0x11",)"
				R"("dir":0,)"
				R"("pmn":250,)"
				R"("pmx":700,)"
				R"("IDNo":1)"
			R"(},)"
			R"({)"
				R"("name":"LeftKnee",)"
				R"("type":"SmartServo",)"
				R"("addr":"0x12",)"
				R"("dir":0,)"
				R"("pmn":280,)"
				R"("pmx":720,)"
				R"("IDNo":2)"
			R"(},)"
			R"({)"
				R"("name":"RightHip",)"
				R"("type":"SmartServo",)"
				R"("addr":"0x13",)"
				R"("dir":1,)"
				R"("pmn":280,)"
				R"("pmx":750,)"
				R"("IDNo":3)"
			R"(},)"
			R"({)"
				R"("name":"RightTwist",)"
				R"("type":"SmartServo",)"
				R"("addr":"0x14",)"
				R"("dir":0,)"
				R"("pmn":280,)"
				R"("pmx":740,)"
				R"("IDNo":4)"
			R"(},)"
			R"({)"
				R"("name":"RightKnee",)"
				R"("type":"SmartServo",)"
				R"("addr":"0x15",)"
				R"("dir":0,)"
				R"("pmn":350,)"
				R"("pmx":780,)"
				R"("IDNo":5)"
			R"(},)"
			R"({)"
				R"("name":"LeftArm",)"
				R"("type":"SmartServo",)"
				R"("addr":"0x16",)"
				R"("mul":700,)"
				R"("dir":0,)"
				R"("kp":250,)"
				R"("ki":100,)"
				R"("kd":250,)"
				R"("pmn":50,)"
				R"("pmx":980,)"
				R"("IDNo":6)"
			R"(},)"
			R"({)"
				R"("name":"RightArm",)"
				R"("type":"SmartServo",)"
				R"("addr":"0x17",)"
				R"("mul":700,)"
				R"("dir":1,)"
				R"("kp":250,)"
				R"("ki":100,)"
				R"("kd":250,)"
				R"("pmn":50,)"
				R"("pmx":980,)"
				R"("IDNo":7)"
			R"(},)"
			R"({)"
				R"("name":"Eyes",)"
				R"("type":"SmartServo",)"
				R"("addr":"0x18",)"
				R"("dir":0,)"
				R"("kp":250,)"
				R"("ki":100,)"
				R"("kd":250,)"
				R"("pmn":100,)"
				R"("pmx":800,)"
				R"("IDNo":8)"
			R"(},)"
			R"({)"
				R"("name":"IMU0",)"
				R"("type":"IMU",)"
				R"("bus":"I2CA",)"
				R"("addr":"0x1D",)"
				R"("poll":"status",)"
				R"("pollHz":100.0,)"
				R"("accIntPin":34,)"
				R"("IDNo":19)"
			R"(},)"
			R"({)"
				R"("name":"AudioOut",)"
				R"("type":"I2SOut",)"
				R"("I2S_PORT":0,)"
				R"("DAC_EN":18,)"
				R"("I2S_BLCK":26,)"
				R"("I2S_DOUT":25,)"
				R"("I2S_LRC":27,)"
				R"("sampleRate":11025)"
			R"(},)"
			R"({)"
				R"("name":"BusPixels0",)"
				R"("type":"BusPixels",)"
				R"("pixPin":"19",)"
				R"("numPix":3,)"
				R"("initial":["002000"],)"
				R"("statusPix0":0,)"
				R"("statusPix1":1,)"
				R"("statusPix2":2)"
			R"(},)"
			R"({)"
				R"("name":"FuelGauge0",)"
				R"("type":"FuelGauge",)"
				R"("bus":"I2CA",)"
				R"("addr":"0x55",)"
				R"("poll":"status",)"
				R"("pollHz":1.0,)"
				R"("extPowSetMs":6000)"
			R"(},)"
			R"({)"
				R"("name":"PowerCtrl",)"
				R"("type":"PowerCtrl",)"
                R"("batteryPackKey":23,)"
				R"("en5V":2,)"
				R"("en5VOnLevel":1,)"
				R"("pwrKeyOffSecs":0.7)"
			R"(})"
		R"(],)"
		R"("AddOns": [)"
		R"(],)"
		R"("Marty1ShortCodes": {)"
			R"("MaxRxMsgLen": 100,)"
			R"("MaxTxMsgLen": 100)"
		R"(},)"
		R"("Publish": {)"
			R"("pubList": [)"
				R"({)"
					R"("type":"HW",)"
					R"("name":"MultiStatus",)"
					R"("trigger":"Time",)"
					R"("topics": ["smart_servos", "accel"],)"
					R"("source":"Multi",)"
					R"("rates": [{)"
						R"("if": "BLE",)"
						R"("protocol": "RICSerial",)"
						R"("rateHz": 10.0)"
					R"(},{)"
						R"("if": "WS",)"
						R"("protocol": "RICSerial",)"
						R"("rateHz": 10.0)"
					R"(}])"
				R"(})"
				R"(,)"
				R"({)"
					R"("type":"HW",)"
					R"("name":"PowerStatus",)"
					R"("trigger":"Time",)"
					R"("topics": ["power_status"],)"
					R"("source":"Multi",)"
					R"("rates": [{)"
						R"("if":"BLE",)"
						R"("protocol":"RICSerial",)"
						R"("rateHz": 1.0)"
					R"(},{)"
						R"("if": "WS",)"
						R"("protocol": "RICSerial",)"
						R"("rateHz": 1.0)"
					R"(}])"
				R"(})"
				R"(,)"
				R"({)"
					R"("type":"HW",)"
					R"("name":"AddOnStatus",)"
					R"("trigger":"Time",)"
					R"("topics": ["addons"],)"
					R"("source":"Multi",)"
					R"("rates": [{)"
						R"("if":"BLE",)"
						R"("protocol":"RICSerial",)"
						R"("rateHz": 10.0)"
					R"(},{)"
						R"("if": "WS",)"
						R"("protocol": "RICSerial",)"
						R"("rateHz": 10.0)"
					R"(}])"
				R"(})"
			R"(])"
		R"(},)"
		R"("Traj": {)"
			R"("init":{)"
				R"("moveTimeMin":400)"
				R"(,"hipAngleMax":30)"
				R"(,"stepLengthMax":50)"
				R"(,"leanMultMax":1)"
				R"(,"DIR_FORWARDS":1)"
				R"(,"DIR_BACKWARDS":-1)"
				R"(,"DIR_LEFT":-1)"
				R"(,"DIR_RIGHT":1)"
				R"(,"moveTime":1500)"
				R"(,"leanAmount":27)"
				R"(,"stepLength":15)"
				R"(,"turn":0)"
				R"(,"leanAngle":29)"
				R"(,"liftAngle":56)"
			R"(},)"
            R"("hwVars":[])"
		R"(},)"
        R"("WorkMgr":{"WorkQ":{"maxLen":10}})"
	R"(})"
R"(})"
};

extern const int RIC_CONFIGURATIONS_LEN = sizeof(RIC_CONFIGURATIONS) / sizeof(const char *);
